### ISSUE TITLE
Unresolved React modules in a Node.js environment

### ISSUE THREAD

**Issue by wigsaparelli** [AlaSQL/alasql#1486]
I'm trying to use alasql in a node module (a Node 16 lambda function on AWS in case that matters) but get the following errors:

![image](https://user-images.githubusercontent.com/26044512/181036018-2a7e8c00-a48e-45fd-8337-145c5570b8d0.png)

But it's not a React project (no React anywhere), it's a Node.js project so not sure why it's trying to resolve various react modules?

I import alasql like this:

`import alasql from 'alasql';`

The project is using the esbuild bundler.
Do I somehow need to tell alasql / npm / esbuild that this is a Node environment not a React environment?  Thanks.

**Comment by wigsaparelli** [comment]
Update:
I have worked around the issue by using the serverless-esbuild plugin's external option as follows to exclude the unwanted modules that could not be resolved.  Can't help but think this shouldn't be required (perhaps separate alasql into multiple packages) but in case others encounter the issue the following worked and everything is fine at runtime using alasql from an AWS lambda function.

```
custom:
    esbuild:
        platform: node
        external:
          # The alasql dependency has some react native modules not applicable to our backend so mark the
          # following as external to exclude from the bundle and avoid 'Could not resolve' build errors.
          - react-native-fs
          - react-native-fetch-blob
```
